Number1=int(input("The First Number is : "))
Number2=int(input("The Second Number is : "))
print(Number1,"+",Number2,"=",Number1+Number2)
print(Number1,"-",Number2,"=",Number1-Number2)
print(Number1,"*",Number2,"=",Number1*Number2)
print(Number1,"/",Number2,"=",int(Number1/Number2))